# Generated by Django 4.0.3 on 2022-03-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
