# Generated by Django 4.0.3 on 2022-03-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
