# Generated by Django 4.0.3 on 2022-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
