# Generated by Django 4.0.3 on 2022-04-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
