# Generated by Django 4.0.3 on 2022-04-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shops', models.CharField(blank=True, max_length=30, null=True)),
                ('shop', models.ForeignKey(help_text='shop of the shopkeeper', on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeeper',
                'verbose_name_plural': 'Shopkeepers',
            },
        ),
    ]
