# Generated by Django 4.0.3 on 2022-04-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timestamp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='title of the shop')),
                ('shop_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Owner of Shop')),
                ('owner', models.CharField(blank=True, max_length=400, null=True, verbose_name='Owner of Shop')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Location of the Shop')),
                ('pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='pincode')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='title of the shop')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='title of the shop')),
                ('product_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='title of the shop')),
                ('mobile_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='title of the shop')),
                ('alter_phone_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='title of the shop')),
                ('mail', models.CharField(blank=True, max_length=400, null=True, verbose_name='title of the shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('timestamp.timestamp',),
        ),
    ]
