# Generated by Django 4.0.3 on 2022-04-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 0, 49, 13, 262154), null=True, verbose_name='datetime at which this object has been first created ')),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 0, 49, 13, 262154), null=True, verbose_name='datetime at which this object was modifed last time')),
            ],
        ),
    ]
